skip_branch_with_pr: true
version: '{build}'
image: Visual Studio 2017

platform:
  - x64

cache:
  - C:\RLibrary
  - C:\RTools
  # saving these seems to be working but I'm not sure it's preventing
  # installing them again every time

clone_folder: c:\projects\cmdstanr
shallow_clone: true
clone_depth: 1


environment:
  HOME: C:\Users\appveyor\
  NOT_CRAN: true
  # versions
  _R_VERSION: "3.6.1"
  _RTOOLS_VERSION: "35"
  # flags
  _R_CHECK_FORCE_SUGGESTS_: false
  _R_CHECK_SYSTEM_CLOCK_: false
  _R_BUILD_FLAGS: "--no-manual"
  _R_CHECK_FLAGS: "--no-manual --as-cran --install-args=--build"
  _CMDSTAN_INSTALL_FLAGS: "-j2 -w"

install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: |
        $ErrorActionPreference = "Stop"
        if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }

        & "C:\\Program Files\\Git\\mingw64\\bin\\curl.exe" -s -o ../R-win.exe -L https://cran.rstudio.com/bin/windows/base/R-$env:_R_VERSION-win.exe
        echo "Running R installer"
        Start-Process -FilePath ..\R-win.exe -ArgumentList "/VERYSILENT /DIR=C:\R" -NoNewWindow -Wait

        & "C:\\Program Files\\Git\\mingw64\\bin\\curl.exe" -s -o ../R-tools-win.exe -L https://cran.rstudio.com/bin/windows/Rtools/Rtools$env:_RTOOLS_VERSION.exe
        echo "Running RTools installer"
        Start-Process -FilePath ..\R-tools-win.exe -ArgumentList /VERYSILENT -NoNewWindow -Wait

        echo "Setting R_LIBS_USER"
        $env:R_LIBS_USER = 'c:\RLibrary'
        if ( -not(Test-Path $env:R_LIBS_USER) ) {
          mkdir $env:R_LIBS_USER
        }

  - SET PATH=C:\\R\\bin\\x64;C:\\Rtools\\bin;C:\\Rtools\\mingw_64\\bin;C:\\Rtools\\mingw_32\\bin;%PATH%
  - echo "Printing toolchain information"
  - g++ --version
  - mingw32-make --version

  - echo "Installing R package dependencies"
  - Rscript -e "sessionInfo()"
  - Rscript -e "install.packages(c('remotes', 'covr', 'knitr'), repos = 'https://cloud.r-project.org')"
  - Rscript -e "options(repos = c(CRAN = 'https://cloud.r-project.org'), download.file.method = 'auto')"
  - Rscript -e "remotes::install_deps(dependencies = TRUE, type='win.binary')"

  - echo "Installing Cmdstan"
  - bash inst/make_cmdstan.sh %_CMDSTAN_INSTALL_FLAGS%

  - echo "Installation done"

build: false

test_script:
  - SET PATH=C:\\R\\bin\\x64;C:\\Rtools\\bin;C:\\Rtools\\mingw_64\\bin;%PATH%
  - echo "Build the package"
  - R.exe CMD build . %_R_BUILD_FLAGS%
  - echo "Check the package"
  - R.exe CMD check .\\cmdstanr_*.tar.gz %_R_CHECK_FLAGS%

on_success:
  - Rscript -e "covr::codecov(line_exclusions = list('R/zzz.R'))"

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
